In [31]:
from numpy import random
import numpy as np

https://numpy.org/doc/stable/search.html?q=random&check_keywords=yes&area=default

## numpy.random.uniform(low=0.0, high=1.0, size=None) 

产生size个均匀分布的浮点数，取值范围为 [low, high), 默认取值范围为[0, 1.0]

In [47]:
random.uniform()

0.12812444792935673

In [48]:
random.uniform(size=1) #返回的是list，默认size为None

array([0.99904052])

In [49]:
random.uniform(5, 6)

5.236088976951976

In [50]:
random.uniform(5, 6, size=(2,3))

array([[5.39658073, 5.38791074, 5.66974604],
       [5.93553907, 5.84631092, 5.31327352]])

## numpy.random.rand(d0,d1,...,dn) 

生成（d0,d1,...,dn) 维的数组，数组的元素取自\[0, 1)上的均匀分布，若没有参数输入，则生成一个数。

与uniform的区别：uniform可以指定均匀分布的取值范围，rand只生成[0,1)之间的数据

In [4]:
random.rand()

0.7604697436690216

In [14]:
random.rand(2)

array([0.21062554, 0.82082741])

In [6]:
random.rand(3,2)

array([[0.01280122, 0.67563865],
       [0.37806253, 0.48737439],
       [0.5339115 , 0.56267612]])

In [7]:
random.rand(3,2,1)

array([[[0.75626279],
        [0.27950295]],

       [[0.34234558],
        [0.06616182]],

       [[0.77131535],
        [0.08313635]]])

## numpy.random.randint(low, high=None, size=None, dtype='I')

生成size个整数，取值区间为\[low, high)，若没有输入high,则取值范围为\[0, low)

In [8]:
random.randint(8)

3

In [9]:
random.randint(8, 10)

9

In [10]:
random.randint(8, size=[1])

array([2])

In [11]:
random.randint(8, size=[3, 2])

array([[6, 6],
       [7, 4],
       [7, 4]])

## numpy.random.random(size=None)

产生\[0.0, 1.0)之间的浮点数(rand也产生0-1之间的浮点数)

In [18]:
random.random(size=(5, 2))

array([[0.16840084, 0.25555261],
       [0.20921024, 0.44288249],
       [0.13964049, 0.24867199],
       [0.36252001, 0.93218443],
       [0.16770406, 0.81104973]])

## numpy.random.choice(a, size=None, replace=True, p=None)

从a(数组) 中选取size(维度)大小的随机数，replace=True表示可重复抽取，p是a中每个数出现的概率

In [19]:
random.choice(5)

3

In [20]:
random.choice([0.2, 0.4])

0.4

In [21]:
random.choice([0.2, 0.4, 0.5], size=(1, 2))

array([[0.5, 0.2]])

In [22]:
random.choice([0.2, 0.4], p=[1, 0])

0.2

In [23]:
random.choice(100, (2, 3, 5), False)

array([[[30, 56, 31, 47, 12],
        [18,  3, 57,  4,  7],
        [81, 59, 71, 21, 94]],

       [[20, 79, 32, 46, 86],
        [65, 64, 97, 68,  9],
        [98, 85, 76, 50, 25]]])

## nump.random.permutation(x) 

随机打乱x中的元素。若x是整数，则打乱arange(x), 若x是一个数组，则按照第一维打乱

In [25]:
random.permutation(5)

array([3, 4, 1, 0, 2])

In [27]:
random.permutation([[1,2,3], [4,5,6]])

array([[4, 5, 6],
       [1, 2, 3]])

## numpy.random.shuffle(x) 

与permutation类似，随机打乱x的元素，若x是整数，则打乱arange(x).但是shuffle会对x进行修改

In [32]:
a = np.arange(5)

In [33]:
random.permutation(a)
a

array([0, 1, 2, 3, 4])

In [34]:
random.shuffle(a)

In [35]:
a

array([3, 2, 0, 1, 4])

## numpy.random.seed(seed=None)

设置随机数种子，使得随机数具有可预见性

In [45]:
random.seed(1)
random.permutation(a)

array([4, 3, 1, 0, 2])

## numpy.random.normal(loc=0.0, scale=1.0, size=None) 

生成符合高斯分布的随机数$ p(x)=\frac{1}{\sqrt{2\pi\sigma^2}}e^{-\frac{(x-u)^2}{2\sigma^2}}$   

In [52]:
mu, sigma = 0, 0.1
np.random.normal(mu, sigma)

0.11522649164302101

In [56]:
a = np.random.normal(mu, sigma, 100)

In [57]:
np.mean(a), np.std(a) # 验证a的均值和标准差

(-0.010279674707896726, 0.09615650497317507)

In [58]:
np.random.normal(mu, sigma, size=(2, 10))

array([[-0.08746708,  0.10468758,  0.02698371,  0.04089153, -0.0337337 ,
         0.01107467,  0.05744002,  0.06866302,  0.17237701, -0.24219711],
       [-0.1501183 ,  0.00463989, -0.00765315,  0.08420919,  0.03674004,
        -0.05112939, -0.07354571, -0.02608521,  0.11737124,  0.02646522]])